endpoint:
  name: Example AXI-Lite module
  bus: AXI-LITE
  enable_atomic: true
  enable_burst: true
  data_size: 32
  addr_size: 32
  prefix_size: 20
  suffix_size: 12

  base_address: 0x20000000

cells:
  - name: status
    type: register
    direction: input
    offset: 0
    size: 4
    bitfields:
      - name: enabled
        offset: 0
        size: 1
      - name: selected_source
        offset: 4
        size: 4
      - name: error_code
        offset: 8
        size: 8
      - name: active_channels
        offset: 16
        size: 16
  - name: config
    type: register
    direction: output
    offset: 4
    size: 4
    bitfields:
      - name: enable
        offset: 0
        size: 1
      - name: select_source
        offset: 4
        size: 4
      - name: active_channels
        offset: 16
        size: 16
  - name: input
    type: fifo
    direction: input
    offset: 12
    size: 4
    mem_size: 32
  - name: output
    type: fifo
    direction: output
    offset: 16
    size: 4
    mem_size: 32
  - name: coeff0
    type: multiregister
    direction: input
    offset: 20
    size: 8
    bitfields:
      - name: coeff
        offset: 0
        size: 64
  - name: coeff1
    type: multiregister
    direction: input
    offset: 28
    size: 8
    bitfields:
      - name: coeff
        offset: 0
        size: 64
  - name: coeff2
    type: multiregister
    direction: input
    offset: 36
    size: 8
    bitfields:
      - name: coeff
        offset: 0
        size: 64
  - name: raw_data
    type: sram
    direction: output
    offset: 64
    size: 16
    mem_size: 16
  - name: interrupts
    type: irq
    direction: output
    offset: 80
    size: 4
  - name: coeffN
    type: multiregister
    direction: input
    offset: 96
    size: 64
    bitfields:
      - name: coeff
        offset: 0
        size: 64
